import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,roll,addClue,deduce,travel,finish,hydrate,CLUES,continuity,time} from '../dist/engine.mjs';
import {getNode,apply,AREAS,ending} from '../dist/story.mjs';
import {pathfind,destination,walkable} from '../dist/world.mjs';
function choose(s,id,match,value=20){const choices=getNode(s,id).choices;const c=typeof match==='number'?choices[match]:choices.find(c=>c.label.includes(match));assert.ok(c,`${id}: ${match}`);assert.ok(!c.disabled);return apply(s,c,c.test?roll(c.test.skill,c.test.dc,value):null);}
function start(){const s=fresh();choose(s,'intro',0);choose(s,'arrival',0);return s;}
function route(s,low=false){choose(s,'keylog',0);travel(s,'dressing');choose(s,'grease',0,low?1:20);choose(s,'contract',0);travel(s,'backstage');choose(s,'plan',0);assert.ok(deduce(s,'grease','plan','route').ok);choose(s,'mercer','Ersatzschlüssel');travel(s,'trap');choose(s,'hatch',0);assert.ok(s.flags.rescued);travel(s,'alley');choose(s,'delivery',0);travel(s,'printer');choose(s,'ledger',0);assert.ok(deduce(s,'keylog','delivery','opportunity').ok);assert.ok(deduce(s,'contract','ledger','motive').ok);return s;}
test('Complete solution remains available with every optional dice check failing',()=>{for(const low of [false,true]){const s=route(start(),low);assert.ok(s.turns<18);assert.equal(finish(s,'rook'),'complete');assert.ok(s.flags.rescued);assert.equal(continuity(s).rookIdentified,true);}});
test('All evidence is unique and repeated clue visits do not charge time',()=>{const s=start();choose(s,'keylog',0);const t=s.turns;choose(s,'keylog',1);assert.equal(s.turns,t);assert.equal(s.clues.filter(k=>k==='keylog').length,1);});
test('Two real independent clues are required for each deduction',()=>{const s=start();addClue(s,'grease');assert.equal(deduce(s,'grease','plan','route').ok,false);addClue(s,'plan');assert.equal(deduce(s,'grease','grease','route').ok,false);assert.equal(deduce(s,'grease','plan','motive').ok,false);assert.ok(deduce(s,'plan','grease','route').ok);assert.deepEqual(s.deductions,['route']);});
test('Optional addresses are gated by actual found leads',()=>{const s=start();assert.throws(()=>travel(s,'trap'));assert.throws(()=>travel(s,'station'));assert.throws(()=>travel(s,'printer'));addClue(s,'ticket');travel(s,'station');assert.equal(s.area,'station');});
test('Failed lock has a guaranteed alternative via the sealed spare key',()=>{const s=start();addClue(s,'grease');addClue(s,'plan');deduce(s,'grease','plan','route');travel(s,'trap');choose(s,'hatch',0,1);assert.ok(s.flags.lockFailed);assert.equal(getNode(s,'hatch').choices[0].disabled,true);choose(s,'lockResult',0);choose(s,'mercer','Ersatzschlüssel');travel(s,'trap');choose(s,'hatch',0);assert.ok(s.flags.rescued);});
test('Successful lock leads to rescue; saved roll result survives reload',()=>{let s=start();addClue(s,'grease');addClue(s,'plan');deduce(s,'grease','plan','route');travel(s,'trap');choose(s,'hatch',0,20);s=hydrate(JSON.parse(JSON.stringify(s)));assert.ok(s.lastSuccess);choose(s,'lockResult',0);assert.ok(s.flags.rescued);assert.ok(s.clues.includes('clara'));});
test('Narrative travel charges same clock as map travel',()=>{const s=start();addClue(s,'ticket');travel(s,'station');const t=s.turns;choose(s,'platform',0);assert.equal(s.turns,t+1);});
test('Initial ride is accounted for without secretly spending a turn',()=>{assert.equal(start().turns,0);});
test('Wrong deductions and reading are timeless',()=>{const s=route(start());const t=s.turns;deduce(s,'keylog','plan','motive');getNode(s,'watson');assert.equal(s.turns,t);});
test('Rook leaves exactly at stated deadline and cannot still be interviewed',()=>{const s=start();s.turns=17;travel(s,'alley');assert.equal(time(s),'22:45');assert.ok(s.flags.late);assert.match(getNode(s,'rook').pages[0],/Platz ist leer/);});
test('The late ending preserves rescue and confirmed evidence',()=>{const s=route(start());s.turns=18;s.flags.late=true;assert.equal(finish(s,'rook'),'late');assert.ok(s.clues.includes('ledger'));assert.ok(s.flags.rescued);});
test('Wrong accusation remains wrong despite collecting all evidence',()=>{for(const suspect of ['mercer','beaumont']){const s=route(start());assert.equal(finish(s,suspect),'wrong');assert.ok(ending(s)[1].includes('in Sicherheit'));assert.ok(!ending(s)[1].includes('klärt später Claras'));}});
test('Correct suspect without a proven chain cannot yield a full success',()=>{const s=start();assert.equal(finish(s,'rook'),'unsupported');});
test('Withholding accusation has its own rescued and unfinished endings',()=>{const s=route(start());assert.equal(finish(s,'none'),'rescue');assert.equal(finish(start(),'none'),'unfinished');});
test('Evidence first without rescuing has distinct timely and late consequences',()=>{for(const late of [false,true]){const s=start();for(const id of ['keylog','delivery','contract','ledger'])addClue(s,id);deduce(s,'keylog','delivery','opportunity');deduce(s,'contract','ledger','motive');s.flags.late=late;assert.equal(finish(s,'rook'),late?'lateUnrescued':'proofOnly');}});
test('A committed result cannot be overwritten',()=>{const s=route(start());finish(s,'rook');finish(s,'mercer');assert.equal(s.ending,'complete');assert.throws(()=>travel(s,'study'));});
test('Game save validation rejects other games and strips forged deductions',()=>{assert.throws(()=>hydrate({version:1,caseId:'nebelpfad'}));const s=start();s.turns=-300;s.clues=['grease','grease','fake'];s.deductions=['motive','route'];s.flags.fake=true;const h=hydrate(s);assert.equal(h.turns,0);assert.deepEqual(h.clues,['grease']);assert.deepEqual(h.deductions,[]);assert.equal(h.flags.fake,undefined);});
test('Completed states round-trip with continuity',()=>{const s=route(start());finish(s,'rook');assert.deepEqual(continuity(hydrate(JSON.parse(JSON.stringify(s)))),continuity(s));});
for(const [area,a]of Object.entries(AREAS))test(`Walkable paths to all interactions in ${a.name}`,()=>{for(const sp of a.spots){const dest=destination(area,sp);assert.ok(dest,sp[0]);const path=pathfind(area,{x:.5,y:.78},dest);assert.ok(path.length||Math.hypot(.5-dest.x,.78-dest.y)<.065,sp[0]);assert.ok(path.every(p=>walkable(area,p.x,p.y)));}});
test('All visible choices point to existing nodes, actions or exploration',()=>{const ids=['intro','arrival','desk','leave','watson','beaumont','rook','rookConfront','keylog','ticket','grease','greaseResult','contract','mercer','spare','plan','rag','agnes','delivery','chase','chaseResult','station','platform','printer','ledger','hatch','lockResult','clara','rescue','epilogue'];for(const complete of [false,true]){const s=complete?route(start()):start();for(const id of ids){const n=getNode(s,id);assert.ok(n.pages.every(t=>typeof t==='string'&&t.length>0),id);for(const c of n.choices)assert.ok(c.next===null||c.next.startsWith('@')||ids.includes(c.next),`${id} -> ${c.next}`);}}});
test('Dice inputs are bounded and critical values do not bypass the stated DC',()=>{assert.throws(()=>roll('observe',12,0));assert.equal(roll('observe',25,20).success,false);assert.equal(roll('observe',5,1).success,true);});

test('The clock wraps correctly after midnight',()=>{const s=start();s.turns=40;assert.equal(time(s),'00:35');});
